docs(*): cleanup and rewrite for v5
pnpm/pnpm.github.io pull request #88
Opened 2021-02-14 17:20 UTC by Nytelife26

2021-02-20 02:58 UTC, Nytelife26 commented
Note that I am still working on this, it just is not my highest priority at the moment.

2021-02-27 19:31 UTC, zkochan commented
It would be better to make many small pull requests. It is hard to review so many changes.

also, this should be finished soon because I want to try to migrate to docusaurus 2

2021-03-02 04:40 UTC, Nytelife26 commented
@zkochan It wouldn't, the pull request handles one scoped change, and overall the workload is the same whether it is in one or many. And, yes, it will be finished today - although, it won't prevent you from doing so whether it is or isn't.

2021-03-02 21:01 UTC, zkochan commented on docs/about-the-package-store.md
> +---
this page can be removed because the global store is not as described here at all. The global store is a content-addressable store.

2021-03-02 23:33 UTC, Nytelife26 commented on docs/about-the-package-store.md
> +---
Resolved in latest commit.

2021-03-03 01:36 UTC, Nytelife26 commented
@zkochan This is now ready to my knowledge. Let me know if you want me to squash the branch commits, or submit a change request if anything needs to be resolved.

2021-03-03 23:59 UTC, zkochan requested changes

2021-03-03 23:59 UTC, zkochan commented on docs/cli/run.md
> +Runs a script defined in the package's metadata.
Metadata might be confusing because it is how the bundle of all the package manifests is called as well. Probably better to say "package's manifest"
```suggestion
Runs a script defined in the package's manifest (`package.json`).
```

2021-03-03 23:59 UTC, zkochan commented on docs/cli/run.md
> +lengthy build process.
no, I don't think that a build process is a good example. This feature was added for watch tasks because they never stop. It is better to keep some concurrency for build tasks, otherwise, the system can potentially crash.

2021-03-03 23:59 UTC, zkochan commented on docs/cli/server.md
> +### --store
I believe this was removed to `store-dir`, which is already documented above.

2021-03-03 23:59 UTC, zkochan commented on docs/cli/stop.md
since the `run` part is optional with any script, this page probably doesn't make sense anymore

2021-03-03 23:59 UTC, zkochan commented on docs/cli/store.md
> -```
why was the example removed?

2021-03-03 23:59 UTC, zkochan commented on docs/cli/test.md
> -### --filter &lt;package_selector>
I think it is useful to have these options duplicated here as well. Or at least a link to the run command that contains them, which you also removed.

2021-03-03 23:59 UTC, zkochan commented on docs/completion.md
> +supports command line tab-completion for Bash, Zsh, Fish, and similar shells.
currently, we only support those three, so I guess "similar shells" is redundant. PowerShell is not supported at the momen.t

2021-03-03 23:59 UTC, zkochan commented on docs/continuous-integration.md
>  pnpm set verify-store-integrity false
this option doesn't make a difference since we use a content-addressable store, so this section may be removed.

2021-03-03 23:59 UTC, zkochan commented on docs/faq.md
> +flatly and uses hard links to create the dependency tree structure.
no, it uses symlinks to create the dependency tree structure.

With hard links, pnpm adds the files to the `node_modules/.pnpm` directory but symlinks are used to interconnect the dependencies.

```suggestion
flatly and uses symlinks to create the dependency tree structure.
```

2021-03-03 23:59 UTC, zkochan commented on docs/faq.md
> +`--preserve-symlinks` flag, however, that approach comes with a plethora of its
"plethora" I learned a new word today😀

2021-03-03 23:59 UTC, zkochan commented on docs/faq.md
> +`.pnpm-store`.  If later the installation is run on disk `B`, an independent
I would still note somehow that the store will be at the root of the disk
```suggestion
`<disk A root>/.pnpm-store`.  If later the installation is run on disk `B`, an independent
```

2021-03-03 23:59 UTC, zkochan commented on docs/faq.md
> +You can do so, by installing it via `pnpm i iterall`, and will be automatically
```suggestion
You can do so, by installing it via `pnpm add iterall`, and will be automatically
```

2021-03-03 23:59 UTC, zkochan commented on docs/faq.md
> +  at /node_modules/inspectpack/2.2.3/node_modules/inspectpack/lib/actions/parse
```suggestion
  at /node_modules/inspectpack@2.2.3/node_modules/inspectpack/lib/actions/parse
```

2021-03-03 23:59 UTC, zkochan commented on docs/faq.md
> +};
we use the Standard style in the pnpm codebase. Though I don't care that much about this example.

2021-03-03 23:59 UTC, zkochan commented on docs/faq.md
> +purpose of pnpm.
I'd be more specific because pnpm has many purposes. I am not sure which one is the primary.

```suggestion
purpose of pnpm's unique node_modules structure.
```

2021-03-03 23:59 UTC, zkochan commented on docs/filtering.md
> +pattern to select a set of packages (`@scope/*`).
it is recommended to quote args with *

```suggestion
pattern to select a set of packages (`"@scope/*"`).
```

2021-03-03 23:59 UTC, zkochan commented on docs/limitations.md
> +2. pnpm can't publish npm packages with `bundledDependencies` yet.
I don't think we will ever support bundledDependencies. They don't work very consistently in npm as well. And you can always bundle your dependencies with a bundler instead of using bundledDependencies.
```suggestion
2. pnpm can't publish npm packages with `bundledDependencies`.
```

2021-03-04 00:00 UTC, zkochan commented
so many changes, still not finished reviewing all.

2021-03-04 00:13 UTC, zkochan commented
If you have a PayPal, I can transfer you some appreciation from our OpenCollective funds.

2021-03-04 01:18 UTC, zkochan requested changes

2021-03-04 01:18 UTC, zkochan commented on docs/symlinked-node-modules-structure.md
> +As you might have noticed, both packages are hard linked into a subfolder inside
this might be better
```suggestion
As you might have noticed, files of both packages are hard linked into a subfolder inside
```

2021-03-04 01:18 UTC, zkochan commented on docs/symlinked-node-modules-structure.md
> +            `-- bar -> ../../../bar@1.0.0/node_modules/bar
```suggestion
            `-- bar -> ../../bar@1.0.0/node_modules/bar
```

2021-03-04 01:18 UTC, zkochan commented on docs/symlinked-node-modules-structure.md
> +            `-- bar -> ../../../bar@1.0.0/node_modules/bar
```suggestion
            `-- bar -> ../../bar@1.0.0/node_modules/bar
```

2021-03-04 01:18 UTC, zkochan commented on docs/workspaces.md
> +reference it as `"foo": "workspace:foo"`.
```suggestion
reference it as `"foo": "workspace:*"`.
```

2021-03-04 01:18 UTC, zkochan commented on docs/workspaces.md
> +example will become: `"bar": "npm:foo@1.0.0"`.
I am not sure looks better without the curly brackets

2021-03-04 01:18 UTC, zkochan commented on docs/workspaces.md
> +* every dependency is a standalone
I am not sure standalone and singleton are the same. It is important to note that it is a singleton because it is important that peer dependencies are singletons in a monorepo

2021-03-04 06:01 UTC, Nytelife26 commented on docs/cli/outdated.md
> -```
It adds unnecessary bulk to the file, would be a pain to clean up because of all the unnecessary escaped HTML that shouldn't be in a code block, and is less helpful than running `pnpm <cmd> --help` in the terminal as well as providing no additional value over the documentation itself as a whole and the example tables found in TL;DR sections.

2021-03-04 06:05 UTC, Nytelife26 commented on docs/cli/run.md
> +lengthy build process.
Build processes are almost always run in parallel. Albeit usually with some degree of constraint, they are. Monorepositories for instance. Sapphire has over 35 packages and builds them all in parallel because, well, could you imagine if they didn't? 

The example isn't the important part. What it demonstrates is.

2021-03-04 06:07 UTC, Nytelife26 commented on docs/cli/recursive.md
> +### --link-workspace-packages
It is, however, I thought it was still worth noting. Especially for cases where it may be disabled in npmrc and someone wishes to override that behaviour without having to change the npmrc.

2021-03-04 06:10 UTC, Nytelife26 commented on docs/cli/server.md
> +### --store
I have absolutely no idea. Both options are still available from CLI, so I'm uncertain as to whether either is deprecated. pnpm's development isn't very well documented. However, since they both exist in CLI, surely both should have a section?

2021-03-04 06:12 UTC, Nytelife26 commented on docs/cli/stop.md
It makes roughly as much sense as documenting `pnpm start` and the like. They're technically lifecycle scripts. Ultimately they don't need to be documented, and honestly, if I were any of the major package managers I wouldn't, but people do.

2021-03-04 06:14 UTC, Nytelife26 commented on docs/cli/store.md
> -```
It's a self-explanatory command. It doesn't require any examples because it does exactly as it says. I will however add a note to the documentation regarding its similarity to standard add, though.

2021-03-04 06:17 UTC, Nytelife26 commented on docs/cli/test.md
> -### --filter &lt;package_selector>
It does say it is an alias of `run test`, so logically speaking it inherits all options of `run`

2021-03-04 06:19 UTC, Nytelife26 commented on docs/completion.md
> +supports command line tab-completion for Bash, Zsh, Fish, and similar shells.
I wasn't referencing PowerShell. Rather, the plethora of other *NIX shells that are essentially functionally equivalent to those main three. Exempli gratia, csh, ash, mksh, pdksh, dash, et cetera.

2021-03-04 06:22 UTC, Nytelife26 commented on docs/faq.md
> +`.pnpm-store`.  If later the installation is run on disk `B`, an independent
It will be at the root of the filesystem or partition, not at the root of the disk, however I will add that note.

2021-03-04 06:23 UTC, Nytelife26 commented on docs/faq.md
> +`--preserve-symlinks` flag, however, that approach comes with a plethora of its
Glad I could be of assistance :)

2021-03-04 06:25 UTC, Nytelife26 commented on docs/faq.md
> +You can do so, by installing it via `pnpm i iterall`, and will be automatically
I'm glad you catch these things. Normally I have a keen eye for proofreading, but it's difficult to maintain for very large rewrites. Bravo :)

2021-03-04 06:27 UTC, Nytelife26 commented on docs/faq.md
> +};
That is standard style. It is universally agreed upon that semicolons should terminate statements in most programming languages since ASI can be very problematic.

2021-03-04 06:31 UTC, Nytelife26 commented on docs/filtering.md
> +pattern to select a set of packages (`@scope/*`).
That is demonstrated in the examples below. When writing generics we leave it down to the user to know what escaping their shell requires.

2021-03-04 06:37 UTC, Nytelife26 commented on docs/npmrc.md
> +access to undeclared dependencies but main libraries themselves do not. With
Isn't this false anyway? I'm fairly sure pnpm creates a fully strict layout, not semistrict, so even dependencies don't have access to them.

2021-03-04 06:42 UTC, Nytelife26 commented on docs/package_json.md
> -```
Really? It's pretty self-explanatory. If optional is true, the peer dependency gets labelled as optional. Do people genuinely need examples for that? I'm not being condescending, just wondering.

2021-03-04 06:45 UTC, Nytelife26 commented on docs/workspaces.md
> +example will become: `"bar": "npm:foo@1.0.0"`.
There is no need for them. It is a key of a JSON object, not a JSON object itself. Putting them in takes up space and looks clunky.

2021-03-04 06:52 UTC, Nytelife26 commented
@zkochan I have left all changes with important discussion points unresolved, so feel free to gloss over those, and then I'll implement whatever verdict we reach. As for PayPal, I do indeed. It is not at all necessary so do not feel pushed to, but I would appreciate it :)

If you so wish, my personal payment page can be found at https://paypal.me/nytelife26

2021-03-05 00:06 UTC, zkochan commented on docs/cli/server.md
> +### --store
`store` is kept for backward compatibility. `store-dir` is the new setting name. `store` should not be mentioned in the docs. The rename happened in pnpm v2 I believe

2021-03-05 00:06 UTC, zkochan commented on docs/cli/stop.md
start makes sense to document because it has a default value `node server.js` (might be a good idea to change this in pnpm v6, to remove start as well)

2021-03-05 00:06 UTC, zkochan commented on docs/package_json.md
> -```
I think they do, especially if their English is not very good. Also, the Yarn docs are more visual in this case https://yarnpkg.com/configuration/manifest

2021-03-05 00:06 UTC, zkochan commented on docs/releasing-apps.md
> -global store without making any requests to the npm registry.
why was this page removed?

2021-03-05 02:24 UTC, Nytelife26 commented on docs/cli/stop.md
Maybe it would be better overall to make a page regarding lifecycle events, similar to the one featured in npm's documentation? Either way, I'll remove stop for now.

2021-03-05 02:26 UTC, Nytelife26 commented on docs/releasing-apps.md
> -global store without making any requests to the npm registry.
It wasn't, it got renamed to docs/production.md since not all projects are applications as such but all projects operate in a production environment, which is what the page is really about.

2021-03-05 02:33 UTC, Nytelife26 commented
I have implemented all the requested changes. This should be ready for merge, however, I will first check that all hyperlinking is valid and report back.

2021-03-05 03:06 UTC, Nytelife26 commented
@zkochan All requested changes have been added. This is now ready to be merged as far as I can tell. As an aside though, I will update the readme with some necessary build steps I encountered that are undocumented.

2021-03-05 09:10 UTC, zkochan approved these changes

2021-03-05 09:10 UTC, merged

2021-03-05 17:48 UTC, zkochan commented
@Nytelife26 you should get an email from OpenCollective.

2021-03-06 13:52 UTC, Nytelife26 commented
@zkochan I have indeed. That's more than I was expecting, thank you very much! This is actually the first non-contract OSS project I've been paid for too, so much appreciated :) I just submitted the invoice as requested in the email.

Have a wonderful day.